### ISSUE TITLE
Need a help for update #662 document

### ISSUE THREAD

**Issue by ccec1t91077** [knuckleswtf/scribe-docs#22]
I don't have much experience on frontend, I can't build the document on local, even I decrease the node version it still showing a crash page on my local environment.

I trying to solve but can't make it working, so need a help for update the document of [#662](https://github.com/knuckleswtf/scribe/pull/662).

**Comment by shalvah** [comment]
You don't need to install it locally. Just edit the needed file directly on github or on github.dev.

**Comment by ccec1t91077** [comment]
Hi, sorry for late PR #27 . I've edit the document, also I found another file which in `scribe_docs\laravel_versioned_docs\version-3.x\reference\20-annotations.md`, almost same content, should I edit this one too?

**Comment by shalvah** [comment]
Ah, don't bother. `version-3.x` is for 3.x version, not supported.
